const data = {
  login: "arslanov-ngc",
  id: 88130228,
  node_id: "MDQ6VXNlcjg4MTMwMjI4",
  avatar_url: "https://avatars.githubusercontent.com/u/88130228?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/arslanov-ngc",
  html_url: "https://github.com/arslanov-ngc",
  followers_url: "https://api.github.com/users/arslanov-ngc/followers",
  following_url: "https://api.github.com/users/arslanov-ngc/following{/other_user}",
  gists_url: "https://api.github.com/users/arslanov-ngc/gists{/gist_id}",
  starred_url: "https://api.github.com/users/arslanov-ngc/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/arslanov-ngc/subscriptions",
  organizations_url: "https://api.github.com/users/arslanov-ngc/orgs",
  repos_url: "https://api.github.com/users/arslanov-ngc/repos",
  events_url: "https://api.github.com/users/arslanov-ngc/events{/privacy}",
  received_events_url: "https://api.github.com/users/arslanov-ngc/received_events",
  type: "User",
  site_admin: false,
  name: "Ismatillo",
  company: null,
  blog: "",
  location: "Andijan, Uzbekistan",
  email: null,
  hireable: null,
  bio: "Front-End Software Engineer. ",
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 6,
  following: 3,
  created_at: "2021-07-29T06:09:32Z",
  updated_at: "2022-08-14T04:22:54Z",
};
export default data;
