const data = [
  {
    login: "javohirbekkhaydarov",
    id: 79502483,
    node_id: "MDQ6VXNlcjc5NTAyNDgz",
    avatar_url: "https://avatars.githubusercontent.com/u/79502483?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/javohirbekkhaydarov",
    html_url: "https://github.com/javohirbekkhaydarov",
    followers_url: "https://api.github.com/users/javohirbekkhaydarov/followers",
    following_url: "https://api.github.com/users/javohirbekkhaydarov/following{/other_user}",
    gists_url: "https://api.github.com/users/javohirbekkhaydarov/gists{/gist_id}",
    starred_url: "https://api.github.com/users/javohirbekkhaydarov/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/javohirbekkhaydarov/subscriptions",
    organizations_url: "https://api.github.com/users/javohirbekkhaydarov/orgs",
    repos_url: "https://api.github.com/users/javohirbekkhaydarov/repos",
    events_url: "https://api.github.com/users/javohirbekkhaydarov/events{/privacy}",
    received_events_url: "https://api.github.com/users/javohirbekkhaydarov/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "umidzhondev",
    id: 81963255,
    node_id: "MDQ6VXNlcjgxOTYzMjU1",
    avatar_url: "https://avatars.githubusercontent.com/u/81963255?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/umidzhondev",
    html_url: "https://github.com/umidzhondev",
    followers_url: "https://api.github.com/users/umidzhondev/followers",
    following_url: "https://api.github.com/users/umidzhondev/following{/other_user}",
    gists_url: "https://api.github.com/users/umidzhondev/gists{/gist_id}",
    starred_url: "https://api.github.com/users/umidzhondev/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/umidzhondev/subscriptions",
    organizations_url: "https://api.github.com/users/umidzhondev/orgs",
    repos_url: "https://api.github.com/users/umidzhondev/repos",
    events_url: "https://api.github.com/users/umidzhondev/events{/privacy}",
    received_events_url: "https://api.github.com/users/umidzhondev/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "BoburAbdukarimov",
    id: 87008144,
    node_id: "MDQ6VXNlcjg3MDA4MTQ0",
    avatar_url: "https://avatars.githubusercontent.com/u/87008144?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/BoburAbdukarimov",
    html_url: "https://github.com/BoburAbdukarimov",
    followers_url: "https://api.github.com/users/BoburAbdukarimov/followers",
    following_url: "https://api.github.com/users/BoburAbdukarimov/following{/other_user}",
    gists_url: "https://api.github.com/users/BoburAbdukarimov/gists{/gist_id}",
    starred_url: "https://api.github.com/users/BoburAbdukarimov/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/BoburAbdukarimov/subscriptions",
    organizations_url: "https://api.github.com/users/BoburAbdukarimov/orgs",
    repos_url: "https://api.github.com/users/BoburAbdukarimov/repos",
    events_url: "https://api.github.com/users/BoburAbdukarimov/events{/privacy}",
    received_events_url: "https://api.github.com/users/BoburAbdukarimov/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "leonofim33",
    id: 94312418,
    node_id: "U_kgDOBZ8X4g",
    avatar_url: "https://avatars.githubusercontent.com/u/94312418?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/leonofim33",
    html_url: "https://github.com/leonofim33",
    followers_url: "https://api.github.com/users/leonofim33/followers",
    following_url: "https://api.github.com/users/leonofim33/following{/other_user}",
    gists_url: "https://api.github.com/users/leonofim33/gists{/gist_id}",
    starred_url: "https://api.github.com/users/leonofim33/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/leonofim33/subscriptions",
    organizations_url: "https://api.github.com/users/leonofim33/orgs",
    repos_url: "https://api.github.com/users/leonofim33/repos",
    events_url: "https://api.github.com/users/leonofim33/events{/privacy}",
    received_events_url: "https://api.github.com/users/leonofim33/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mrcyberj0hn",
    id: 97495311,
    node_id: "U_kgDOBc-pDw",
    avatar_url: "https://avatars.githubusercontent.com/u/97495311?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mrcyberj0hn",
    html_url: "https://github.com/mrcyberj0hn",
    followers_url: "https://api.github.com/users/mrcyberj0hn/followers",
    following_url: "https://api.github.com/users/mrcyberj0hn/following{/other_user}",
    gists_url: "https://api.github.com/users/mrcyberj0hn/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mrcyberj0hn/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mrcyberj0hn/subscriptions",
    organizations_url: "https://api.github.com/users/mrcyberj0hn/orgs",
    repos_url: "https://api.github.com/users/mrcyberj0hn/repos",
    events_url: "https://api.github.com/users/mrcyberj0hn/events{/privacy}",
    received_events_url: "https://api.github.com/users/mrcyberj0hn/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nasimdjanovich",
    id: 102401252,
    node_id: "U_kgDOBhqE5A",
    avatar_url: "https://avatars.githubusercontent.com/u/102401252?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nasimdjanovich",
    html_url: "https://github.com/nasimdjanovich",
    followers_url: "https://api.github.com/users/nasimdjanovich/followers",
    following_url: "https://api.github.com/users/nasimdjanovich/following{/other_user}",
    gists_url: "https://api.github.com/users/nasimdjanovich/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nasimdjanovich/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nasimdjanovich/subscriptions",
    organizations_url: "https://api.github.com/users/nasimdjanovich/orgs",
    repos_url: "https://api.github.com/users/nasimdjanovich/repos",
    events_url: "https://api.github.com/users/nasimdjanovich/events{/privacy}",
    received_events_url: "https://api.github.com/users/nasimdjanovich/received_events",
    type: "User",
    site_admin: false,
  },
];

export default data;